import { Feat } from 'src/libs/shared/definitions/models/feat';
import { FeatTaken } from 'src/libs/shared/definitions/models/feat-taken';

export class FeatsState {
    public levelFeats: [
        Map<string, Feat>,
        Map<string, Feat>,
        Map<string, Feat>,
        Map<string, Feat>,
        Map<string, Feat>,
        Map<string, Feat>,
        Map<string, Feat>,
        Map<string, Feat>,
        Map<string, Feat>,
        Map<string, Feat>,
        Map<string, Feat>,
        Map<string, Feat>,
        Map<string, Feat>,
        Map<string, Feat>,
        Map<string, Feat>,
        Map<string, Feat>,
        Map<string, Feat>,
        Map<string, Feat>,
        Map<string, Feat>,
        Map<string, Feat>,
        Map<string, Feat>,
    ];
    public levelCountAs: [
        Map<string, boolean>,
        Map<string, boolean>,
        Map<string, boolean>,
        Map<string, boolean>,
        Map<string, boolean>,
        Map<string, boolean>,
        Map<string, boolean>,
        Map<string, boolean>,
        Map<string, boolean>,
        Map<string, boolean>,
        Map<string, boolean>,
        Map<string, boolean>,
        Map<string, boolean>,
        Map<string, boolean>,
        Map<string, boolean>,
        Map<string, boolean>,
        Map<string, boolean>,
        Map<string, boolean>,
        Map<string, boolean>,
        Map<string, boolean>,
        Map<string, boolean>,
    ];
    public levelTakenFeats: [
        Map<string, Feat>,
        Map<string, Feat>,
        Map<string, Feat>,
        Map<string, Feat>,
        Map<string, Feat>,
        Map<string, Feat>,
        Map<string, Feat>,
        Map<string, Feat>,
        Map<string, Feat>,
        Map<string, Feat>,
        Map<string, Feat>,
        Map<string, Feat>,
        Map<string, Feat>,
        Map<string, Feat>,
        Map<string, Feat>,
        Map<string, Feat>,
        Map<string, Feat>,
        Map<string, Feat>,
        Map<string, Feat>,
        Map<string, Feat>,
        Map<string, Feat>,
    ];
    public characterFeatsTaken: Array<{ levelNumber: number; gain: FeatTaken; feat: Feat; temporary: boolean }>;

    constructor() {
        this.levelFeats = [
            new Map<string, Feat>(),
            new Map<string, Feat>(),
            new Map<string, Feat>(),
            new Map<string, Feat>(),
            new Map<string, Feat>(),
            new Map<string, Feat>(),
            new Map<string, Feat>(),
            new Map<string, Feat>(),
            new Map<string, Feat>(),
            new Map<string, Feat>(),
            new Map<string, Feat>(),
            new Map<string, Feat>(),
            new Map<string, Feat>(),
            new Map<string, Feat>(),
            new Map<string, Feat>(),
            new Map<string, Feat>(),
            new Map<string, Feat>(),
            new Map<string, Feat>(),
            new Map<string, Feat>(),
            new Map<string, Feat>(),
            new Map<string, Feat>(),
        ];
        this.levelTakenFeats = [
            new Map<string, Feat>(),
            new Map<string, Feat>(),
            new Map<string, Feat>(),
            new Map<string, Feat>(),
            new Map<string, Feat>(),
            new Map<string, Feat>(),
            new Map<string, Feat>(),
            new Map<string, Feat>(),
            new Map<string, Feat>(),
            new Map<string, Feat>(),
            new Map<string, Feat>(),
            new Map<string, Feat>(),
            new Map<string, Feat>(),
            new Map<string, Feat>(),
            new Map<string, Feat>(),
            new Map<string, Feat>(),
            new Map<string, Feat>(),
            new Map<string, Feat>(),
            new Map<string, Feat>(),
            new Map<string, Feat>(),
            new Map<string, Feat>(),
        ];
        this.levelCountAs = [
            new Map<string, boolean>(),
            new Map<string, boolean>(),
            new Map<string, boolean>(),
            new Map<string, boolean>(),
            new Map<string, boolean>(),
            new Map<string, boolean>(),
            new Map<string, boolean>(),
            new Map<string, boolean>(),
            new Map<string, boolean>(),
            new Map<string, boolean>(),
            new Map<string, boolean>(),
            new Map<string, boolean>(),
            new Map<string, boolean>(),
            new Map<string, boolean>(),
            new Map<string, boolean>(),
            new Map<string, boolean>(),
            new Map<string, boolean>(),
            new Map<string, boolean>(),
            new Map<string, boolean>(),
            new Map<string, boolean>(),
            new Map<string, boolean>(),
        ];
        this.characterFeatsTaken = new Array<{ levelNumber: number; gain: FeatTaken; feat: Feat; temporary: boolean }>();
    }
}
