/* eslint-disable @typescript-eslint/no-magic-numbers */
export const Defaults = {
    maxCharacterLevel: 20,
    abilityBaseValue: 10,
    dcBaseValue: 10,
    expPerLevel: 1000,
    familiarAbilities: 2,
    startingGold: 15,
    wornToolsInventoryBulkLimit: 2,
    defaultFamiliarSpeed: 25,
    playerMessageTTL: 600,
    foundryMessageTTL: 500,
    colorAccent: '#465A8C',
    colorAccentRGB: '25, 118, 210',
    tooltipDelay: 100,
    maxFocusPoints: 3,
    maxHeroPoints: 3,
    mobileBreakpointPx: 992,
    waitForServiceDelay: 100,
    maxInvestedItems: 10,
    maxInvestedAeonStones: 1,
    maxDyingValue: 4,
    closingMenuClearDelay: 500,
    smallBonus: 1,
    mediumBonus: 2,
    largeBonus: 4,
    updateURL: 'http://api.github.com/repos/bukiro/PECS/releases/latest',
};
